[build]
  command = "pnpm run build:docs && vite build"
  publish = "dist"

[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  command = "vite build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
